### ISSUE TITLE
For DateRangeQueries, the base triple pattern (?variable ex:property ?value) must not be generated

### ISSUE THREAD

**Issue by tfrancart** [SteinerPascal/sparnatural-port#83]
@SteinerPascal similar to the situation you have with MapWidget, when the TimeWidget generates date ranges query (https://docs.sparnatural.eu/Querying-date-ranges) then the widget generates the entire query pattern (actually a serie of UNION clauses) and the base triple pattern generated in RdfJsQuery (e.g. `?Person_1 ex:property ?Country_1`) should not be generated.

I think this raises the question of the the benefits of decoupling the base triple pattern generation from the pattern generated by the widget. I don't think the two should be decoupled, and I suggest that the widget is responsible for generating the **entire** triple pattern + FILTERs + VALUES. A default implementation can be provided that generates the base triple pattern, but that could be overriden in special situations.

This would solve your issue with MapWidget, and also mine with date range queries. What do you think ?

**Comment by SteinerPascal** [comment]
Okay I see and I can agree. I have two suggestions. 
1. A default implementation of the pattern is implemented by the class AbstractWidget and can be overridden if necessary.
2. Having some properties in the abstract class indicating if the default triples should be created.

I strongly lean towards the first proposal =)

**Comment by tfrancart** [comment]
> A default implementation of the pattern is implemented by the class AbstractWidget and can be overridden if necessary.

Yes, perfect

**Comment by SteinerPascal** [comment]
Okay i just realized that comes with one big drawback. The query can then be only generated when there is actually an Abstract widget. So before there is a Widget, it's not possible to create the query. The same counts if the widget is removed or so...

**Comment by SteinerPascal** [comment]
Okay I'm going solve it the following way:

The Sparql generator generates the default triples but IF there is an abstract Widget. It has the possiblity to override the the triples.

**Comment by tfrancart** [comment]
It is also related to the question of generating the query from the widgets or UI structure or from the query JSON data structure. If the query is generated from the JSON data structure, it is decoupled from the UI and we don't have to worry about it.

I will come back to this with another question about the implementation of the defaultLabelProperty (#76)

**Comment by SteinerPascal** [comment]
hehe i knew that was coming. ;) Yes you are right but there is actually a deeper problem or philosophy question behind it. 
Follwing scenario:
A user starts to select the StartClass (the first part of the query gets generated), then he starts to select the Endclass(another sparql part gets created) and selects a predicate class. Now the widget comes in and "overrides/changes" the already generated query. That might be confusing since it can possibly change the whole query. The same when removing the widget but it might still have the power to override the query... 
You guys have some use cases where the query gets triggered automatically. That's going to be weird for the user to see some results when selecting the startclass but then having different query and results as soon as the widget is chosen.

The whole thing builds on the problem that, we can not know, which widget a user will select before he/she has actually done it. 

Now we can say that a query generation only be generated when a row is actually "Completed". Like also shown in the UI styling.
OR
For now i just add some properties in the abstract class where we can disable the generation of a StartClass,ObjectProp,EndClass triple.
